# Generated by Django 3.1.5 on 2021-02-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='currency',
            name='ecb_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ecb updated'),
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='exchange rate'),
        ),
        migrations.AddField(
            model_name='currency',
            name='last_fetched',
            field=models.DateTimeField(blank=True, help_text='Last successful update from ecb rss feed.', null=True, verbose_name='last fetched'),
        ),
    ]
